Added outlier detection with iterativetrimming
experimental-design/bofire pull request #227
Opened 2023-06-28 09:01 UTC by swagataroy123

Hi @jduerholt ,
I have added the robust GP outlier as in this paper [(https://arxiv.org/abs/2011.11057]((https://arxiv.org/abs/2011.11057))

2023-06-28 13:16 UTC, jduerholt requested changes
Thx, I let some comments.

2023-06-28 13:16 UTC, jduerholt commented on bofire/data_models/outlier_detection/outlier_detection.py
> +class IterativeTrimming(OutlierDetection):
Please add a docstring in which you mention the method and the paper and explain the parameters.

2023-06-28 13:16 UTC, jduerholt commented on bofire/outlier_detection/mapper.py
> +SURROGATE_MAP: Dict[Type[data_models.OutlierDetection], Type[OutlierDetection]] = {
```suggestion
OUTLIER_MAP: Dict[Type[data_models.OutlierDetection], Type[OutlierDetection]] = {
```

2023-06-28 13:16 UTC, jduerholt commented on bofire/outlier_detection/mapper.py
> +    cls = SURROGATE_MAP[data_model.__class__]
```suggestion
    cls = OUTLIER_MAP[data_model.__class__]
```

2023-06-28 13:16 UTC, jduerholt commented on bofire/outlier_detection/api.py
add here the import of the outlier detection modeule

2023-06-28 13:16 UTC, jduerholt commented on bofire/outlier_detection/outlier_detection.py
> +    def detect(self, experiments: pd.DataFrame):
```suggestion
    def detect(self, experiments: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
```

2023-06-28 13:16 UTC, jduerholt commented on tests/bofire/outlier_validation/test_outlier_detection.py
call it in the tests exactly as in the the main structure, `outlier_validation` --> `outlier_detection`

2023-06-28 13:16 UTC, jduerholt commented on tests/bofire/outlier_validation/test_outlier_detection.py
> +    Trimmed, outliers = ITGP.detect(experiments=experiments)
```suggestion
    trimmed, outliers = ITGP.detect(experiments=experiments)
```

2023-06-28 13:16 UTC, jduerholt commented on tests/bofire/outlier_validation/test_outlier_detection.py
> +    assert len(experiments) == len(Trimmed) + len(outliers)
can you also check it it was able to finde most of the outliers?

2023-06-28 13:16 UTC, jduerholt commented on tests/bofire/outlier_validation/test_outlier_detection.py
> +@pytest.mark.parametrize(
we do not need the parameterization here. just write everything starting in line 20 into  the test_IterativeTrimming method, and remove the argument `experiments` from it.

2023-06-28 13:17 UTC, swagataroy123 commented on bofire/data_models/outlier_detection/api.py
> +    AnyOutlierDetection = Union[OutlierDetection,IterativeTrimming]
I just copied it from api of data_models/surrogates

2023-06-28 13:18 UTC, swagataroy123 commented on bofire/outlier_detection/api.py
yeah ruff messed up something

2023-06-28 13:43 UTC, swagataroy123 commented
> Thx, I let some comments.

I have answered them

2023-06-28 13:50 UTC, jduerholt commented on bofire/data_models/outlier_detection/outlier_detection.py
> +class IterativeTrimming(OutlierDetection):
Please use google type docstrings

2023-06-28 13:52 UTC, jduerholt commented on bofire/data_models/outlier_detection/api.py
> +    AnyOutlierDetection = Union[OutlierDetection,IterativeTrimming]
It is not needed here, please remove it.

2023-06-28 13:56 UTC, jduerholt commented
Please also add a specs module as shown here: https://github.com/experimental-design/bofire/blob/main/tests/bofire/data_models/specs/surrogates.py and add the serialization and deserialization tests.

2023-06-28 13:57 UTC, swagataroy123 commented
> Furthermore, a notebook under tutorials would be nice in which the ITGP outlier detection stuff is demonstrated based on the ITGP paper.
> 
> Call it outlier_detection.ipynb

2023-06-29 13:23 UTC, jduerholt approved these changes
Looks good to me.

2023-06-29 13:23 UTC, merged