Patch
experimental-design/bofire pull request #235
Opened 2023-07-03 12:15 UTC by swagataroy123

Hi @jduerholt , this pull request adds outlier detection to the BO strategy

2023-07-06 11:37 UTC, jduerholt commented on bofire/outlier_detection/outlier_detection.py
> +from bofire.surrogates.api import map
```suggestion
import bofire.surrogates.api import as surrogates
```

2023-07-06 11:38 UTC, jduerholt commented on bofire/outlier_detection/outlier_detection.py
> +        model = map(self.base_gp)
```suggestion
        model = surrogates.map(self.base_gp)
```

2023-07-07 08:02 UTC, jduerholt requested changes
Hi Swagata,

thank you very much for this PR. I went through the implementation and let some comments. If you have questions, feel free to reach out to me.

2023-07-07 08:02 UTC, jduerholt commented on bofire/data_models/strategies/predictives/botorch.py
> +    outlier_detection_specs: Optional[List[AnyOutlierDetection]] = None
We could also think about providing the sceduling already here, then we do not need to create the `detect_outliers` keyword in tell. 

My idea would be the following: 

- Create an attribute called `min_experiments_before_outlier_check` (mabye someting more handy, I am very uncreative) that specifies how many minimal experiments has to be available before outlier checking.
- Create an argument which specifies in which schedule they are checked. And then we determine if we are in schedule via the modulo operator.

2023-07-17 09:09 UTC, swagataroy123 commented on tests/bofire/strategies/dummy.py
> +    def _get_acqfs(self, n: int):
We need a dummystrategy from botorchstrategy to test outlier detection in test_strategy.py

2023-08-07 11:25 UTC, jduerholt requested changes
Looks good, only some small changes, then it will be done ;)

2023-08-07 11:25 UTC, jduerholt commented on bofire/benchmarks/benchmark.py
> +        self.OutlierPrior = OutlierPrior
```suggestion
        self.outlier_prior= OutlierPrior
```

2023-08-07 11:25 UTC, jduerholt commented on bofire/benchmarks/benchmark.py
> +        OutlierPrior: Optional[AnyOutlierPrior] = None,
```suggestion
        outlier_prior: Optional[AnyOutlierPrior] = None,
```

2023-08-07 11:25 UTC, jduerholt commented on bofire/benchmarks/benchmark.py
> +                Y.loc[ix2, "y"] = Y.loc[ix2, "y"] + uniform(
This will not work, the name of the output feature(s) is not always `y`

2023-08-07 11:25 UTC, jduerholt commented on bofire/benchmarks/benchmark.py
> +                    no_outliers
Why `no_outliers`? or stands `no_outliers` for numer of outliers? Then please rename to `n_outliers`.

2023-08-07 11:25 UTC, jduerholt commented on bofire/benchmarks/benchmark.py
> +            if self.OutlierPrior.type == "tOutlierPrior":
No need for `tOutlierPrior`. Uniform and Normal should be sufficient. Please also move the sampling of the outliers into the specific classes above.

2023-08-07 11:25 UTC, jduerholt commented on tests/bofire/outlier_detection/test_outlier_detection.py
> +    assert len(experiments1[experiments1["valid_y"] == 0]) > n_outlier / 2
Can you also add a test for the functional testing `OutlierDetections`? class to see if detection outliers for several outputs in parallel works?

2023-08-07 11:25 UTC, jduerholt commented on bofire/data_models/outlier_detection/outlier_detections.py
> +    def _check_compability(self, inputs: Inputs, outputs: Outputs):
Can you add tests for the errors raised here? You can get inspiration from the tests from `BotorchSurrogates` when we test the compatibility method there.

2023-08-11 09:42 UTC, jduerholt requested changes
Hi Swagata,

now it is really almost done!!!

Only a few small things.

Best,

Johannes

2023-08-11 09:42 UTC, jduerholt commented on tests/bofire/outlier_detection/test_outlier_detection.py
> +    with pytest.raises(ValueError):
```suggestion
    with pytest.raises(ValueErro, message=...):
```

Can you also add here the messages of the individual errors raised, I know it is not done everywhere, but I try to force myself to catch it in new parts that are added.

2023-08-11 09:42 UTC, jduerholt commented on tests/bofire/outlier_detection/test_outlier_detection.py
> +    with pytest.raises(ValueError):
Do it then for the whole test.

2023-08-11 09:42 UTC, jduerholt commented on bofire/data_models/outlier_detection/outlier_detections.py
> +    detectors: List[AnyOutlierDetector]
```suggestion
    detectors: Annotated[List[AnyOutlierDetector], Field(min_items=1]
```
This ensure, that the detectors list is not empty, we should also test that the `OutlierDetectors` functional model  can work with just one detector.

2023-08-11 09:42 UTC, jduerholt commented on bofire/data_models/outlier_detection/outlier_detections.py
> +
```suggestion
@validator(detectors)
def validate_detectors(cls,v,values):
    used_output_feature_keys = list(
            itertools.chain.from_iterable([detector.outputs.get_keys() for detector in v])
        )
        if len(set(used_output_feature_keys)) != len(used_output_feature_keys):
            raise ValueError("Output feature keys are not unique across surrogates.")
        return v

```

We need a validator here that ensures that the output detectors have different output features. And also a test for it.

2023-08-11 09:42 UTC, jduerholt commented on tests/bofire/outlier_detection/test_outlier_detection.py
> +def test_OutlierDetections():
Can you add a second test here in which the both detectors have different input features. For example the first one is working on input feature `x_1` and the second on `x_2`. Of course in experiments both feature are present but the surrogates in the indivdual ITGP detectors work on different input sets.

2023-08-14 07:21 UTC, jduerholt approved these changes

2023-08-14 07:22 UTC, merged