added calibration metric
experimental-design/bofire pull request #253
Opened 2023-08-07 12:55 UTC by swagataroy123

@jduerholt ,
Added calibration metric from https://github.com/aspuru-guzik-group/dionysus/blob/main/dionysus/uncertainty_metrics.py

2023-08-07 20:52 UTC, jduerholt requested changes
Thanks, I left some comments.

2023-08-08 14:13 UTC, swagataroy123 commented on bofire/surrogates/diagnostics.py
> +    This implementation is taken from Ax: https://github.com/aspuru-guzik-group/dionysus/blob/main/dionysus/uncertainty_metrics.py
Don't know. Copied from the fisher format. Will just remove it

2023-08-08 14:13 UTC, swagataroy123 commented on tests/bofire/surrogates/test_diagnostics.py
> +            if cv_results.results[i].standard_deviation is not None:
otherwise i get assert nan = nan error

2023-08-08 14:15 UTC, swagataroy123 commented on tests/bofire/surrogates/test_diagnostics.py
> +
Sould i make a seperate dictionary for UQ_metrics like metrics

2023-08-08 14:15 UTC, swagataroy123 commented on bofire/surrogates/diagnostics.py
> +            + np.sum(np.square(predicted - observed) / standard_deviation)  # type: ignore
I just copied it. maybe they missed a bracket. I will double check and correct accordingly

2023-08-09 13:11 UTC, swagataroy123 commented on bofire/surrogates/diagnostics.py
> +            + np.sum(np.square(predicted - observed) / standard_deviation)  # type: ignore
i think u r right

2023-08-10 13:41 UTC, jduerholt requested changes
You are right, we should have seperate dictionaries and enums. Thanks for the hint.

2023-08-10 13:41 UTC, jduerholt commented on bofire/surrogates/feature_importance.py
> +        RegressionMetricsEnum.PEARSON_UQ: 1.0,
Remove them here, it makes no sense for permutation importance. You are right, we need a second enum and second dictionary.

2023-08-10 13:41 UTC, jduerholt commented on bofire/data_models/enum.py
> +    PEARSON_UQ = "PEARSON_UQ"
Create a new enum named UQRegressionMetricsEnum and move the UQ Metrics into this,

2023-08-10 13:41 UTC, jduerholt commented on bofire/data_models/enum.py
> +    NLL = "NLL"
Just remove the complete NLL metric.

2023-08-10 13:41 UTC, jduerholt commented on bofire/data_models/surrogates/trainable.py
> +    RegressionMetricsEnum.PEARSON_UQ: MaximizeObjective,
this has to be then updated with the new type.

2023-08-10 13:41 UTC, jduerholt commented on bofire/surrogates/diagnostics.py
> +    RegressionMetricsEnum.PEARSON_UQ: _pearson_UQ,
we also need to update here, then with `UQRegressionMetricsEnum`

2023-08-10 13:41 UTC, jduerholt commented on bofire/surrogates/feature_importance.py
> +        RegressionMetricsEnum.PEARSON_UQ: 1.0,
We would then iterate here only over the standard regression metrices.

2023-08-10 13:41 UTC, jduerholt commented on tests/bofire/surrogates/test_diagnostics.py
> +    for metric in metrics.keys():
you have to iteratre here only over the uq metrices, as only there the warning is raised.

2023-08-11 09:02 UTC, jduerholt commented on tests/bofire/surrogates/test_diagnostics.py
> +        cv.get_UQ_metric(metric=metric)
```suggestion
        m = cv.get_UQ_metric(metric=metric)
        assert type(m)==float
```

2023-08-11 09:59 UTC, jduerholt requested changes

2023-08-11 09:59 UTC, jduerholt commented on bofire/surrogates/diagnostics.py
> +All_metrics = {**metrics, **UQ_metrics}
```suggestion
all_metrics = {**metrics, **UQ_metrics}
```

2023-08-11 09:59 UTC, jduerholt commented on bofire/surrogates/diagnostics.py
> +        return All_metrics[metric](self.observed.values, self.predicted.values, self.standard_deviation)  # type: ignore
```suggestion
        return all_metrics[metric](self.observed.values, self.predicted.values, self.standard_deviation)  # type: ignore
```

2023-08-14 07:22 UTC, jduerholt approved these changes

2023-08-14 07:23 UTC, merged