Fragment filter
experimental-design/bofire pull request #270
Opened 2023-08-25 08:39 UTC by jduerholt

This PR adds a method that can be used to get only the contained fragments for a list of smiles. This can then be used to intitialize the `Fragments` object only with the needed fragments. One could also think about adding a method which returns only the fragments with variance in it.

2023-08-26 12:11 UTC, jduerholt commented
@simonsung06 : can you have a look?

2023-08-26 12:47 UTC, simonsung06 commented
Sorry for the delay. I left a comment on the test. Can you see it?

2023-08-26 20:37 UTC, jduerholt commented
No problem, but I cannot see any comment.

2023-08-27 23:49 UTC, simonsung06 requested changes
I like the feature. minor comment

2023-08-28 06:13 UTC, jduerholt commented on tests/bofire/data_models/test_molfeatures.py
> +    mf.get_contained_fragments(smiles)
We can do this, could be better. I will add this later.

2024-11-27 15:39 UTC, closed without merging