Active Learning
experimental-design/bofire pull request #361
Opened 2024-03-07 13:31 UTC by jdridder

This PR adds the feature of **_active learning_** meaning bayesian optimization with **_pure exploration_** to the repo. It includes a new predictive strategy named `ActiveLearningStrategy` that uses the acquisition function `[qNegIntegratedPosteriorVariance]` [link](https://botorch.org/api/_modules/botorch/acquisition/active_learning.html#qNegIntegratedPosteriorVariance) to choose new candidate points depending on how strongly they will reduce the variance of the posterior. Like proposed in this [issue](https://github.com/experimental-design/bofire/issues/331).

This new strategy can handle single and multiple output models. For multiple output models specific weights for each output variable can be supplied.

Furthermore, a tutorial notebook is provided that illustrates the usage of the `ActiveLearningStrategy` for single and multiple output cases. Please check the code for further adjustments. Hopefully, we can merge the PR soon.

2024-03-14 14:50 UTC, jduerholt requested changes
Hi @jdridder,

thank you very much. I let a few comments. Should be easily done. There are also a few merge conflicts that has to be resolved.

Best,

Johannes

2024-03-14 14:50 UTC, jduerholt commented on bofire/data_models/strategies/predictives/active_learning.py
> +    weights: Optional[Dict[str, float]] = Field(default_factory=lambda: None)
```suggestion
    weights: Optional[Dict[str, PositiveFloat]] = Field(default_factory=lambda: None)
```

Concerning the weights:
- you can import `PositiveFloat` from pydantic
- I think we concluded that we want to have the `weights` attribute under the acquisition function `qNegIntPostVar` as attribute as it is specific to this acquisition function and other active learning acquisition functions would not use this. So can you move it?
- We need then a `model_validator` with mode `"after"` in which we check that if `weights` are provided, the keys match the keys of the output features:
```python
@model_validator(mode="after")
def validate_acquisition_function(self):
   if isinstance(self.acquisition_function, qNegIntPosVar):
       if self.acquisition_function.weights is not None:
           if sorted(self.acquisition_function.weights.keys()) != sorted(self.domain.outputs.get_keys()):
               raise ValueError(balabala)
   return self
```

2024-03-14 14:50 UTC, jduerholt commented on tests/bofire/data_models/specs/strategies.py
> +specs.add_invalid(
This does not hold anymore as invalid, but you should modify it to test if the error is thrown if the keys of the weights does not match the output feature keys.

2024-03-14 14:50 UTC, jduerholt commented on bofire/strategies/predictives/active_learning.py
> +    def _get_acqfs(self, n) -> List[AcquisitionFunction]:
Can you create a file `tests/bofire/strategies/predictives/test_active_learning.py` in which you test this method? And also check that the posterior transform etc. is correctly generated?

2024-03-15 16:47 UTC, jdridder reviewed
Thanks @jduerholt. I reviewed your suggestions and made the changes accordingly. Feel free to check for merging or to suggest further improvements. Also, please take a look at the conflicting files as I do not have write access to resolve the conflicts.

Regards,
JD

2024-03-19 20:50 UTC, jduerholt requested changes
Hi JD,

looks really good to me. Regarding the merge conflicts: you can just update your local main branch to the current upstream main, switch back to this development branch and do a `git merge main`, and resolve the conflicts. In case of problems, I can also do it for you. 

Best,

Johannes

2024-03-19 20:50 UTC, jduerholt commented on tests/bofire/strategies/test_active_learning.py
> +def test_weight_keys_qNegIntPosVar():
Hmm, this test is not necessary, or? You are testing this already via the `add_invalid` ...

2024-09-30 16:30 UTC, jduerholt requested changes
Hey @jdridder,

I found one of the reasons why the tests are failing. See comment below. Just fix it and push again, then I will look for the second. 

Best,

Johannes

2024-09-30 16:30 UTC, jduerholt commented on tests/bofire/data_models/specs/strategies.py
> +    message="The provided keys for the weights must match the keys of the output features.",
This is the wrong error message, it should be: "The keys provided for the weights do not match the required keys of the output features." Have a look at `bofire/data_models/strategies/predictives/active_learning.py`

2024-10-02 12:37 UTC, jduerholt requested changes
Hi @jdridder,

it took me a while, but I found it. You have to register the `ActiveLearningStrategy` in `data_models/strategies/actual_strategy_type.py` as `ActualStrategy`.

Then it should work.

Best,

Johannes

2024-10-04 08:26 UTC, jdridder reviewed
Hi @jduerholt,

thanks for finding the error :) .
All missing changes are made. The last commits are stashed and forced-pushed into one final commit `[Bug fix tests ActiveLearning]`.
 Tests now run successfully.
Looking forward to merging.

Regards,
JD

2024-10-07 07:15 UTC, jduerholt approved these changes
Thank you very much @jdridder!

2024-10-07 07:15 UTC, merged