Linear Interpolation
experimental-design/bofire pull request #443
Opened 2024-10-02 13:23 UTC by jduerholt

This PR introduces GPs that are perfoming on linear interpolated two one-dimensional curves.

2024-10-04 08:44 UTC, bertiqwerty requested changes
Hi Johannes, Thanks. Can you please add some documentation? And an example would be great. Thanks.

2024-10-07 07:24 UTC, bertiqwerty approved these changes
After discussing with Johannes we decided to first merge this. Johannes will a more extensive documentation afterwards.

2024-10-08 07:47 UTC, jduerholt commented on bofire/kernels/shape.py
> +        return torch.exp(-dists)
We use it for monotonicall increasing 1 dimensional functions. On these functions, the wasserstein distance is equal to the integral over the absolute difference between the two functions.

2024-10-08 20:42 UTC, CompRhys commented on bofire/kernels/shape.py
> +        return torch.exp(-dists)
I would think that that should be explained in the docstring or rename to call it a laplacian_kernel. I was recently reading https://link.springer.com/article/10.1007/s10472-023-09883-w and so was drawn to this class but it's not as general as the name suggests.

2024-10-09 06:52 UTC, jduerholt commented on bofire/kernels/shape.py
> +        return torch.exp(-dists)
I will add it in the docstring. Why laplacian kernel?

2024-10-09 16:06 UTC, CompRhys commented on bofire/kernels/shape.py
> +        return torch.exp(-dists)
https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.laplacian_kernel.html the cdist p=1 returns `|x-y||_1` which is the same distance as used in the laplacian_kernel although the prefactors and constants are different.

2024-10-30 13:29 UTC, merged