I optimality criterion
experimental-design/bofire pull request #485
Opened 2024-12-18 10:55 UTC by Osburg

This PR adjusts the I optimality criterion suggested in #428 to the new structure of doe from #448

2024-12-22 22:07 UTC, Osburg commented
@dlinzner-bcs I tried to implement your suggestion from #483, does it roughly look like you imagined?
Cheers
Aaron :)

2025-01-10 09:17 UTC, dlinzner-bcs commented
Hi Aaron! Oh very nice thank you! I will check it out.

2025-01-30 15:22 UTC, dlinzner-bcs commented
Hi Aaron! That covers the use case i had in mind really well. Thank you :) i added a surrogate use case as a test. So all is left is to merge main again 🙈

2025-01-30 18:06 UTC, Osburg commented
At your service 🫡. I guess all these pyright errors are not my fault, right? :D 
@dlinzner-bcs pls feel free to approve and merge if you are okay with the changes.

Cheers
Aaron :)

2025-01-31 08:16 UTC, dlinzner-bcs requested changes
Thank you @Osburg! Looks great and will be very helpful to us!

2025-01-31 08:16 UTC, dlinzner-bcs commented on bofire/strategies/doe/objective.py
> +            warnings.warn(
Would this also work? This seems like less code.
 ```   
    data_model = data_models.DoEStrategy(
        domain=domain,
        optimization_strategy="partially-random",
        criterion=SpaceFillingCriterion(delta=delta),
        ipopt_options={"maxiter": 500, "disp": 0},
    )
    sampler = strategies.DoEStrategy(data_model=data_model)
    result = sampler.ask(n_space_filling_points).values
```

2025-01-31 08:52 UTC, Osburg commented on bofire/strategies/doe/objective.py
> +            warnings.warn(
Agree that this would be nicer, but I think this leads to circular imports :/

2025-01-31 09:41 UTC, dlinzner-bcs approved these changes
This is good to go :) Thank you @Osburg.

2025-01-31 09:45 UTC, merged